### PR TITLE
Allow custom client_secret validation via validate_client_secret()

### PR DESCRIPTION
**Pull request by fabfuel**
I do not want to store client secrets as plain text. Therefore I need Flask Authlib to use a custom validation method, that validates the given client secret internally.

This PR adds support for clients providing a custom validation method, as it is already supported for e.g. redirect_uri (via `validate_redirect_uri()`) or scopes (via `validate_scopes()`)

### CODE REVIEW

**Comment by frol** [comment]
Your implementation is odd as there is some code right after your changes which still checks for `if hasattr(client, 'client_secret') and client.client_secret != client_secret:`.

Why cannot you implement `client_secret` as a custom type with overloaded `__eq__` & `__ne__` operators?

**Comment by fabfuel** [comment]
Seriously a custom type? Because this would be super complicated. 
Why are there `validate_redirect_uri()` and `validate_scopes()`, which - in your opinion - could be implemented as custom types.

**Comment by frol** [comment]
Well, `validate_redirect_uri` and `validate_scopes` are defined on `OAuth2RequestValidator` rather than on the `Client` model. It would be great then to follow the style.

P.S. Tests are also important if you want to ensure that nobody breaks your feature in future.

**Comment by fabfuel** [comment]
Sorry, I guess my comment wasn't perfectly clear.
I'm talking about the optional usage of these optional methods on the `Client` model, here:
https://github.com/fabfuel/flask-oauthlib/blob/2cd39634c005c9141c9c9ee4e9052324e6fda3f5/flask_oauthlib/provider/oauth2.py#L919-L920

and here:
https://github.com/fabfuel/flask-oauthlib/blob/2cd39634c005c9141c9c9ee4e9052324e6fda3f5/flask_oauthlib/provider/oauth2.py#L959-L960

Please explain, what exactly you mean with "follow the style".
My implementation follows the same style in terms of design. The `Client` method is used, if it exists.
In terms of syntax, it doesn't. Because instead of just checking if the attribute exists, it's checking if it is `callable` and it's not directly returning the result, to the preserve debug log message.

**Comment by frol** [comment]
1. The checks are implemented in dedicated methods, and given your implementation, I would put these lines into a dedicated method and refactor so the `client.client_secret != client_secret` is not checked if the validator is implemented: https://github.com/fabfuel/flask-oauthlib/blob/2cd39634c005c9141c9c9ee4e9052324e6fda3f5/flask_oauthlib/provider/oauth2.py#L662-L671
2. They don't require any default implementation (your change doesn't require the `validate_client_secret` on the client either, so why do you put it there in the first place?)
3. What kind of situation is that when `validate_client_secret` is defined, but not callable? `validate_redirect_uri` and `validate_scopes` only check for the attribute to be defined. Is `validate_client_secret` special in this respect?

**Comment by fabfuel** [comment]
1. Now I got your point - you're right, thats odd :slightly_smiling_face: I will change that.
2. Yes, it is up to the specific `Client` implementation, if a validation method is implemented or not. Exactly like for validating scopes or redirect url. 
I put it there to be able to validate a hashed client secret. Currently, the validation is only possible if the secret is stored in plain text (what IMHO is a serious issue, because it encourages people to store secrets in plain text) - or with a custom type.
3. Yes, that would be a nasty situation. And no, it's not special in this respect. I will remove the strict validation to align with the existing code.

**Comment by frol** [comment]
2. It is absolutely fine if you put it in your own Client implementation, but it just seems irrelevant in the base.Client.

**Comment by frol** [comment]
@fabfuel Beautiful! Thank you for making it!

**Comment by fabfuel** [comment]
Regarding 2.
This was only in the tests. As there are only functional tests so far (as far as I saw), I implemented this simple secret validation in the Client, to get this path covered. Anyway, I removed that.

I now refactored the client secret validation to a separate method: `_validate_client_secret`.
Please let me know, if I should move the unit tests to another location.

**Comment by frol** [comment]
@fabfuel Oh, I missed that that was in tests, sorry.

**Pull request closed without merging**
