### PR TITLE
Allow a validate class to be passed into the OAuth2 Provider to be us…

### PR DESCRIPTION
**Pull request by claweyenuk**
…ed instead of requiring an instance of a class

I am using a client secret hash instead of a client secret which requires a slightly different authenticate_client function in the validator class.  I would like to just pass in the validator class instead of creating an instance so I don't have to worry about all the getters and setters getting checked

### CODE REVIEW

**Comment by lepture** [comment]
It doesn't work. Please fix it.

**Comment by claweyenuk** [comment]
Strange, I ran the code successfully and went through a full authorization code grant.  Trying an alternate approach, I have yet to test this though

**Comment by lepture** [comment]
@claweyenuk btw, you should add a test and documentation for it.

**Comment by claweyenuk** [comment]
Is there a good way to run tests locally?  I gave a quick go with `python setup.py test` and running nose in the base and test directories, but no luck.  Can you point me in the right direction?

**Comment by claweyenuk** [comment]
@lepture I should have tagged you above ^

**Comment by claweyenuk** [comment]
nvm, I just looked at a travis job and saw it was `nosetests -s`

**Pull request merged**
