### PR TITLE
Improve debug messages in `validate_bearer_token()`

### PR DESCRIPTION
**Pull request by indera**
I was having issues with the token validation and decided to add a couple of changes to improve the displayed messages:

### CODE REVIEW

**Comment by indera** [comment]
To enable logging I have added at the top of my file:

```
flog = logging.getLogger('flask_oauthlib')
flog.addHandler(logging.StreamHandler(sys.stdout))
flog.setLevel(logging.DEBUG)
```

**Comment by lepture** [comment]
Why do you need those print in the tests?

**Comment by indera** [comment]
@lepture I was debugging the tests so I was adding "print" statements -- see my latest commit where I removed all print messages https://github.com/lepture/flask-oauthlib/pull/271/commits/3f71212f60bae29c83824e2a2190410440011c30

**Comment by lepture** [comment]
@indera Hi, I've updated the codebase. Better close this PR with a new PR.

**Pull request closed without merging**
